# --- Main Colors ---
background            #0b160f
foreground            #d9e6db
cursor                #d9e6db
cursor_text_color     #0b160f

selection_background  #494900
selection_foreground  #e7e78f

url_color             #91d5ad

# --- ANSI Colors ---
color0                #0b160f
color1                #ffb4ab
color2                #91d5ad
color3                #cbcb76
color4                #cbcc57
color5                #91d5ad
color6                #cbcb76
color7                #d9e6db

color8                #cbcb76
color9                #93000a
color10               #045233
color11               #494900
color12               #494900
color13               #494900
color14               #045233
color15               #b5ccbb

# --- Starship Prompt Bubbles ---
color255              #494900
color254              #cbcc57
color253              #494900
color252              #cbcb76
color251              #045233
color250              #91d5ad
color249              #93000a
color248              #ffb4ab

color232              #e8e870
color233              #323200
color234              #e7e78f
color235              #323200
color236              #acf2c7
color237              #003921
color238              #ffdad6
color239              #690005
color240              #e8e870

# Matched with unthemed light/dark
color243              #cbcc57
color244              #ffb4ab
color245              #374b3e

# --- UI Elements ---
active_tab_foreground   #323200
active_tab_background   #cbcc57
inactive_tab_foreground #e8e870
inactive_tab_background #494900

active_border_color     #cbcc57
inactive_border_color   #7f9686

# --- Marks ---
mark1_foreground        #1d1d00
mark1_background        #e8e870
mark2_foreground        #1d1d00
mark2_background        #e7e78f
mark3_foreground        #002112
mark3_background        #acf2c7
