# --- Main Colors ---
background            #15130c
foreground            #e7e2d5
cursor                #e7e2d5
cursor_text_color     #15130c

selection_background  #4c472b
selection_foreground  #ebe3bd

url_color             #a7d0b7

# --- ANSI Colors ---
color0                #15130c
color1                #ffb4ab
color2                #a7d0b7
color3                #cec7a2
color4                #d5c871
color5                #a7d0b7
color6                #cec7a2
color7                #e7e2d5

color8                #4a473a
color9                #93000a
color10               #294e3b
color11               #4c472b
color12               #4f4700
color13               #4c472b
color14               #294e3b
color15               #ccc6b5

# --- Starship Prompt Bubbles ---
color255              #4f4700
color254              #d5c871
color253              #4c472b
color252              #cec7a2
color251              #294e3b
color250              #a7d0b7
color249              #93000a
color248              #ffb4ab

color232              #f2e48a
color233              #373100
color234              #ebe3bd
color235              #353117
color236              #c2ecd2
color237              #113726
color238              #ffdad6
color239              #690005
color240              #f2e48a

# Matched with unthemed light/dark
color243              #d5c871
color244              #ffb4ab
color245              #4a473a

# --- UI Elements ---
active_tab_foreground   #373100
active_tab_background   #d5c871
inactive_tab_foreground #f2e48a
inactive_tab_background #4f4700

active_border_color     #d5c871
inactive_border_color   #959181

# --- Marks ---
mark1_foreground        #201c00
mark1_background        #f2e48a
mark2_foreground        #1f1c05
mark2_background        #ebe3bd
mark3_foreground        #002113
mark3_background        #c2ecd2
