bind_address = '127.0.0.1'
web_port = 1701
websocket_port = 9001
try_vaapi = true
try_nvenc = true
auto_start = false
no_gui = false
wayland_support = true
virtual_keys_profiles = '[{"name":"New Profile","items":[]}]'
