[font]
size = 12.0

[font.normal]
family = "FiraCode Nerd Font"
style = "Regular"

[window]
opacity = 0.8
decorations="Full"
dynamic_padding=true
blur=true

[scrolling]
multiplier=4
[selection]
save_to_clipboard = true
